spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/study_db?useSSL=false&serverTimezone=Asia/Seoul
        username: ysi
        password: 1234

mybatis:
    mapper-locations: classpath:/mapper/*.xml

spring.jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate.format_sql: true

jwt:
    secret: hello.world.ee.ff




