spring:

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/study_db?useSSL=false&serverTimezone=Asia/Seoul
        username: ysi
        password: 1234
    security:
            oauth2:
                client:
                    registration:
                        github:
                            client-id: a67142256bd698af3808
                            client-secret: 5fb5e5d685bb5ace0eb59f741f5aa90df7a906ac
                            redirect-uri: http://localhost:8080/github/callback


    mail:
        host: smtp.naver.com
        port: 465  # SMTP 포트 (보통 587 또는 465를 사용)
        username: did756984
        password: did4037018
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true  # STARTTLS 사용
                        isSSL: true
#                    custom:
#                            frontend_url: http://localhost:3000/signup # 원하는 프론트엔드 URL로 변경

mybatis:
    mapper-locations: classpath:/mapper/*.xml

spring.jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate.format_sql: true

jwt:
    secret: hello.world.ee.ff
    algorithm: "HS256"





