spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/study_db?useSSL=false&serverTimezone=Asia/Seoul
        username: ysi
        password: 1234

    mail:
        host: smtp.naver.com
        port: 465  # SMTP 포트 (보통 587 또는 465를 사용)
        username: did756984@naver.com
        password:  # Naver 이메일 비밀번호
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true  # STARTTLS 사용
                        isSSL: true

mybatis:
    mapper-locations: classpath:/mapper/*.xml

spring.jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate.format_sql: true

jwt:
    secret: hello.world.ee.ff


